---
title: 
author: "Hong Pan"
date: "`r format(Sys.time(), '%d %B %Y')`"

abstract: 
thanks: 'Code and data are available at: https://github.com/HongTrista/folder.'
bibliography: references.bib

output:
  bookdown::pdf_document2:
  toc: no


header-includes:
 - \usepackage{float}
 - \floatplacement{figure}{H}
 - \floatplacement{table}{H}
---


```{r}
#### Workspace setup ####
# install.packages("ggplot2")
library(ggplot2) #for drawing nice figures

#install.packages("ggpubr")
library(ggpubr) #for combing figures in one graph


#install.packages("knitr")
library(knitr) # create table

# install.packages("tidyverse")
library(tidyverse) #filter dataset


install.packages("kableExtra")
library(kableExtra)# position of table

```






#import dataset
```{r}
simulated_dataset<-read_csv('~/Desktop/simulated_data.csv')
```


# layoff

```{r}


ggarrange(p1, p2, ncol = 2, nrow = 1)

simulated_dataset%>%
  ggplot(aes(q3_layoff, fill =q1_city)) + 
  geom_bar(position = "dodge")+
  facet_wrap(~q2_type)+
  ylab("Number of responses")+
  xlab("Number of laid-offs")+
  ggtitle('Layoff situation in Peterborough')+
  theme_minimal()
  




#Takeaways: 
#1. Brantford(shutdown city): overall, except for the value of 0, other levels are all larger than Peterborough. 
# By segment, although quick service type has a higher number to lay off 1 to 4 employees, it has a lower number of laying more than 10  and a higher number of without laying people.

#2. Peterborough(reopen city): In both types of services, the highest proportion of without firing people. However, table-services perform worse than quick-services.
#3. Conclude: Brantford is suffering from Covid 19
```

#total sales & revenue & cost

```{r}
#total sales
simulated_dataset%>%
  ggplot(aes(q4_total_sales, fill =q1_city)) + 
  geom_bar(position = "dodge")+
  ylab("Number of responses")+
  xlab("Total sales")+
  ggtitle('The total sales in the two cities compared to the previous month')+
  scale_x_discrete(limits = c("Lose more than 10%", "Lose 5% ~ 10%", "Roughly unchanged","Earn 5% ~ 10%","Earn more than 10%"))+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90))




#revenue
simulated_dataset%>%
  ggplot(aes(q6_revenue, fill =q1_city)) + 
  geom_bar(position = "dodge")+
  ylab("Number of responses")+
  xlab("Revenue")+
  ggtitle('Revenue changes due to covid 19')+
  scale_x_discrete(limits = c("Decreased more than 25%", "Decreased by 5% – 25%", "Roughly unchanged","Increased by  5% – 25%",
                              "Increased more than 25%","Prefer not to say"))+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90))



#Cost:

simulated_dataset%>%
  ggplot(aes(q11_cost, fill =q1_city)) + 
  geom_bar(position = "dodge")+
  ylab("Number of responses")+
  xlab("Cost")+
  ggtitle('Degree of cost increase')+
  scale_x_discrete(limits = c("0 – 25%", "25% - 50%", "More than 50%","Our costs have decreased after the pandemic",
                              "Prefer not to say"))+
  theme_minimal()+
   theme(axis.text.x = element_text(angle = 90))
  






#Takeaways (total sales):
#1. In Brantford, the vast majority of restaurants are losing money more than 5% compared to last month's sales.
#2. In Peterborough (Peterborough), a large proportion of restaurants have started to get bettered, and most restaurants can maintain the status of the previous month and even start to earn income.



#Takeaways(revenue):
#Although there are some positives responses, most of the restaurants have lost revenue to a certain extent. Especially in Brantford, the entire city is shut down, and most restaurants lose more than 25%. Although the situation in Peterborough is better by comparison, most restaurants have lost revenue from 5%-25%.


#Takeaways(cost):
#Two cities have a very close result, but overall, around 80% of the restaurant's responses that their cost has increased. And, the highest proportion replies their cost increased within 25%.


#Conclude:
# Although most restaurants in the two cities suffer from the pandemic, reopened can help the restaurant reduce their pressure to some extent.

```


```{r}
#Peterborough
p_table <- data.frame(table(simulated_dataset[simulated_dataset$q1_city=="Peterborough",]$q4_total_sales))%>%
  mutate(pct=round(Freq/sum(Freq)*100))

label_p<-paste(p_table$Var1,p_table$pct)%>%
  paste("%",sep = "")
#pie(slices,labels = label_p,col=rainbow(length(label_p)),
   # main = "Pie chart of total sales in Peterborough")



#Brantford
b_table <- data.frame(table(simulated_dataset[simulated_dataset$q1_city=="Brantford",]$q4_total_sales))%>%
  mutate(pct=round(Freq/sum(Freq)*100))

label_b<-paste(b_table$Var1,b_table$pct)%>%
  paste("%",sep = "")
#pie(slices,labels = label_p,col=rainbow(length(label_p)),
    #main = "Pie chart of total sales in Brantford")




#Side-By-Side Pie Charts
par(mfrow = c(1,3))
pie(p_table$Freq,labels = label_p,col=rainbow(length(label_p)),
    main = "Pie chart of total sales in Peterborough",cex=0.6,cex.main=1)
pie(b_table$Freq,labels = label_b,col=rainbow(length(label_b)),
    main = "Pie chart of total sales in Brantford",cex=0.6,cex.main=1)




#Takeaways:

```

#survival

```{r}

data.frame(table(simulated_dataset$q7_survive,simulated_dataset$q1_city))%>%
  ggplot(aes(Var1, Freq,fill=Var1)) +
    geom_bar(stat = "identity")+
  facet_wrap(~Var2)+
  theme(axis.text.x = element_text(angle = 90))+
  scale_x_discrete(limits = c("Less than 3 months", "3 to 6 months", "Longer than 6 months","Unknown","Prefer not to say"))+
  ylab("Number of responses")+
  xlab("Expected survival time")
  

#Takeaways:
# 40% of restaurants in Brantford need help! The data clearly shows many restaurants are quickly approaching permanent closures. We are now two months into the shutdown, which is too late for many, but countless companies can still be saved if we move fast enough to help them. 

# The situation in Peterborough is much better. Around half of the restaurants said they would survive more than 6 months.

```

# operation
```{r}
simulated_dataset%>%
  ggplot(aes(q8_operation, fill =q1_city)) + 
  geom_bar()+
  facet_wrap(~q2_type)+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Number of responses")+
  xlab("Cost")+
  ggtitle('Current profitability of overall operation')+
  scale_x_discrete(limits = c("Operating at a loss", "Breaking even", "Profit between 0% and 2%","Profit between 2% and 5%","Profit of 5% or more","Prefer not to say"))





simulated_dataset%>%
  ggplot(aes(q8_operation, fill =q1_city)) + 
  geom_bar(position = "dodge")+
  facet_wrap(~q2_type)+
  ylab("Number of responses")+
  xlab("Cost")+
  ggtitle('Current profitability of overall operation')+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_x_discrete(limits = c("Operating at a loss", "Breaking even", "Profit between 0% and 2%","Profit between 2% and 5%","Profit of 5% or more","Prefer not to say"))
  

#Takeaways:
# Table-service restaurants more suffer in shut down city.


```


#q9:recover
```{r}
#need to reorder the column in table
t1<-simulated_dataset%>%
  filter(q1_city=="Peterborough")

table(t1$q13_CEWS,t1$q9_recover)%>%
  prop.table()%>%
  kable("html", align = 'clc', caption = 'Peterborough')%>%
  kable_styling(full_width = F, position = "float_left")
  
  
  
t2<-simulated_dataset%>%
  filter(q1_city=='Brantford')

table(t2$q13_CEWS,t2$q9_recover)%>%
  prop.table()%>%
  kable("html", align = 'clc', caption = 'Brantford')%>%
  kable_styling(full_width = F, position = "right")


#Takeaway:
#1. For both cities, we can see that around 35% of the restaurants that received wage subsidies said they would back to normal operation before between a year and 18 months, followed by around 12% of restaurants that said they need 7-12 months to recover.
#This illustrates how much the pandemic has hit the foodservice industry.

#2. Under the circumstance of receiving a wage subsidy, comparing Peterborough with Brantford, we can see that Peterborough has a higher percentage indicating that they will recover in less than 6 months. 
```

#q12: government support
```{r}
p3<-simulated_dataset%>%
  filter(simulated_dataset$q1_city=="Peterborough")%>%
  ggplot(aes(q12_support, fill =q12_support)) + 
  geom_bar()+
  facet_wrap(~q2_type)+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Number of responses")+
  xlab("Need government support or not")+
  ggtitle('Peterborough: whether need support')+
  scale_x_discrete(limits = c("Yes", "No", "I do not know"))+
  ylim(0,25)


p4<-simulated_dataset%>%
  filter(simulated_dataset$q1_city=="Brantford")%>%
  ggplot(aes(q12_support, fill =q12_support)) + 
  geom_bar()+
  facet_wrap(~q2_type)+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Number of responses")+
  xlab("Need government support or not")+
  ggtitle('Brantford: whether need support')+
  scale_x_discrete(limits = c("Yes", "No", "I do not know"))+
  ylim(0,25)




ggarrange(p3, p4, ncol = 2, nrow = 1)

#Takeaway:
#For both cities, in the face of these pressing financial challenges, this is not surprising that around 60% of survey respondents said their foodservice business requires additional financial support. By segment, table-service restaurants and quick-service restaurant's situations are quite similar in Peterborough.  But in Brantford, we can see table service restaurants are suffering from the city shutdown and more difficulty than quick-service restaurants.


```














































