---
title: "Untitled"
output: pdf_document


header-includes:
 - \usepackage{float}
 - \floatplacement{figure}{H}
 - \floatplacement{table}{H}
---

```{r,include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
#### Workspace setup ####
library(janitor) # Create tables
library(tidyverse)
library(kableExtra)


```





#import dataset
```{r}
simulated_survey1_dataset <- read.csv( here('outputs/survey/simulated_first_survey.csv'))
```

#q3 & 5
```{r,echo=FALSE,warning=FALSE}
t1<-simulated_survey1_dataset %>%
  tabyl(q1_city, q3_category)%>%
  adorn_totals("row", name = "Total Average")%>%
  adorn_totals("col")%>%
  adorn_percentages("row")%>%
  adorn_pct_formatting(digits=1)%>%
  adorn_ns()%>%
  adorn_title("combined",row_name = "City", col_name = "Category") %>% 
  rename(
    City = `City/Category`
  )
t1$Total <- NULL


t2<-simulated_survey1_dataset %>%
  tabyl(q1_city, q5_nature)%>%
  adorn_totals("row", name = "Total Average")%>%
  adorn_totals("col")%>%
  adorn_percentages("row")%>%
  adorn_pct_formatting(digits=1)%>%
  adorn_ns()%>%
  adorn_title("combined",row_name = "City", col_name = "Nature") %>% 
  rename(
    `Table Service` = `Table-service restaurant`,
    `Quick Service` = `Quick-service restaurant`
  )
t2$`City/Nature` <- NULL
t2$Total <- NULL
kable(
  list(t1, t2),
  caption = 'Category and Nature of Restarants',
  booktabs = TRUE, valign = 't', 
  align = "ccccc"
)

#Takeaway: similar category and nature for restaurants in Peterborough and Brantford
```



#q2


```{r,echo=FALSE}
#bar chart
#simulated_survey1_dataset%>%
#  ggplot(aes(q2_employees, fill =q1_city)) + 
#  geom_bar(position = "dodge")+
#  ylab("Number of responses")+
#  xlab("Number of employees")+
#  ggtitle('Number of employees in the two cities')+
#  theme_minimal()+
#  scale_x_discrete(limits = c("Less than 5", "5 -10", "10 - 30","30 - 50","Prefer not to say"))+
#  guides(fill=guide_legend(title="City"))


#table
t3<-simulated_survey1_dataset %>%
  tabyl(q1_city, q2_employees)%>%
#  adorn_totals("row", name ="Total Average")%>%
#  adorn_totals("col")%>%
  adorn_percentages("row")%>%
  adorn_pct_formatting(digits=1)%>%
  adorn_ns()%>%
  adorn_title("combined",row_name = "City", col_name = "Employees")


 kable(t3[,c(1,5,4,2,3,6)],caption = 'Number of Employees',
        booktabs=TRUE,valign='t', align = "cccccc")%>%
  kable_styling()



# Takeaways:
# From the bar chart, we can see a similar pattern in both cities-the more employees, the fewer restaurants. Most restaurants have between 5 and 10 employees.
 
#From table, restaurants in both cities are basically small and medium-sized, and most restaurants employ less than 30 employees.
```




#q4

```{r,echo=FALSE}
data.frame(table(simulated_survey1_dataset$q4_sales,simulated_survey1_dataset$q1_city))%>%
  ggplot(aes(Var1, Freq,fill=Var2)) +
  theme_minimal()+
    geom_bar(stat = "identity",position = position_dodge(), width = 0.7)+
   theme(plot.title = element_text(hjust = 0.5)) +
  ylab("Number of Responses")+
  xlab("Sales amount")+
  ggtitle("Average monthly sales of restaurants")+
  guides(fill=guide_legend(title="City"))+
  scale_x_discrete(limits = c("$0 - $25,000", "$25,000 - $50,000", "$50,000 - $80,000","$80,000 - $110,000","$110,000 - $150,000","Prefer not to say"))+
  theme(axis.text.x=element_text(size=rel(0.8), angle=15))




#Takeaways:
#Similar pattern for two cities. The data mainly fall in the range of $0-$25,000 and $25,000 - $ 50,000. After that, the higher the sales, the fewer restaurants.

```




#q6


```{r,echo=FALSE}
simulated_survey1_dataset%>%
  ggplot(aes(q6_customers, fill =q1_city)) + 
  geom_bar(position = "dodge")+
  ylab("Number of responses")+
  xlab("Number of customers")+
  ggtitle('Number of customers served at the same time')+
  theme_minimal()+
  scale_x_discrete(limits = c("Less than 10","10 - 20", "20 - 40", "40 -70","70 -100","Prefer not to say"))+
  guides(fill=guide_legend(title="City"))+
  theme(axis.text.x=element_text(size=rel(0.8), angle=15))


#table
t4<-simulated_survey1_dataset %>%
  tabyl(q1_city, q6_customers)%>%
  adorn_totals("row")%>%
  adorn_totals("col")%>%
  adorn_percentages("row")%>%
  adorn_pct_formatting(digits=1)%>%
  adorn_ns()%>%
  adorn_title("combined",row_name = "City", col_name = "Customers")


 kable(t4[,c(1,6,2,3,4,5,7,8)],caption = 'Number of customers served at the same time',
        booktabs=TRUE,valign='t')%>%
  kable_styling()

 
 #Takeaways:
 # On average, restaurants in the two cities can serve 10 to 40 people at the same time.
```

```{r}
library(finalfit)
```
```{r}
#https://finalfit.org/articles/all_tables_examples.html

#https://stackoverflow.com/questions/32593434/r-change-row-order
f_survey <- simulated_survey1_dataset %>% 
  summary_factorlist("q1_city", c("q3_category","q5_nature","q2_employees","q4_sales","q6_customers"),
                     p = FALSE, 
                     add_dependent_label = TRUE,
                     dependent_label_prefix = "",
                     add_col_totals = TRUE,
                     include_row_missing_col = FALSE,
                     col_totals_rowname = "",
                     total_col = FALSE) %>%
  rename(
    Responses = ` `
  ) #%>% 
 f_survey$q1_city <- NULL
#  f_survey$Responses[c(1:5,9,8,6,7,10,11,13,14,15,12,16,21,17,18,19,20,22),] # Manually change the order of the factor levels to have a better visualization 
 f_survey <- f_survey[c(1:5,9,8,6,7,10,11,13,14,15,12,16,21,17,18,19,20,22),] %>% 
    mutate(` ` = c("Total Samples","Restaurant Category","","Restaurant Nature","","Number of Employees","","","","","Average Monthly Sales","","","","","","Restaurant Capacity","","","","",""))

f_survey %>% 
  kable(
    caption = "Test",
    booktabs = TRUE,
    linesep = "",
    col.names = 
  )
  mutate(group = c("","Restaurant Category","","Restaurant Nature","","Number of Employees","","","","","Average Monthly Sales","","","","","","Restaurant Capacity","","","","","")) #%>% 
  
  kable( f_survey[,c(4,1,2,3)],caption = "Summary Statistics for First Survey",
         booktabs = TRUE,
         valign='t'
         ) 
  #%>% 
  #  kable_styling(latex_options = "hold_position", protect_latex = FALSE)
  
```








