---
title: "Test script"
author: "Hong Shi"
date: "2/8/2021"
output: pdf_document
---
```{r}
library(tidyverse)
library(rvest)
```
```{r}
raw_data <- read_html("https://en.wikipedia.org/wiki/List_of_cities_in_Ontario")
write_html(raw_data, "inputs/wiki/ontariocities.html")
```
```{r}
#Read in our saved data
raw_data <- read_html("inputs/wiki/ontariocities.html")
parse_data_inspection <- 
  raw_data %>% 
  html_nodes("td:nth-child(7) , .headerSort:nth-child(7) , td:nth-child(8) , td:nth-child(4) , td:nth-child(3) , td:nth-child(2) , td:nth-child(1) , .headerSort:nth-child(8) , .headerSort:nth-child(4) , .headerSort:nth-child(3) , .headerSort:nth-child(2) , .headerSort:nth-child(1)") %>% 
  html_text()


```

```{r}
head(parse_data_inspection,18)
```
```{r}
parse_data_inspection
parse_data_inspection2 <- slice(parse_data_inspection, 1:312)
```


```{r}
class(parse_data_inspection)
```

```{r}
parsed_data <- tibble(raw_text = parse_data_inspection) %>% 
  slice(1:312)
parsed_data
```
```{r}
spread(parsed_data, key = "raw_text")
```

```{r}
library(tidyr)
```
```{r}
df_long <- pivot_longer()
```


```{r}
df <- tibble(
  x = 1:3,
  y = c("a", "d,e,f", "g,h"),
  z = c("1", "2,3,4", "5,6")
)
df
```




