---
title: "STATCAN_test"
author: "Hong Shi"
date: "2/12/2021"
output: pdf_document
---

```{r}
library(tidyverse)
library(here)
```

```{r}

```

```{r}
# We get the Employment by industry, annual, census metropolitan areas from Statistics Canada:
# https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1410009801
# install.packages("cansim")
library(cansim)
library(ggrepel)
statscan_employment <- get_cansim("282-0131") # This is the CANSIM table code of the employment data 
```
```{r}
# have a glance of the data
head(statscan_employment)
```

```{r}
# save the raw data of Employment by industry, annual, census metropolitan areas 
write_csv(statscan_employment, here::here("inputs/data/raw_statscan_employment.csv"))
```
```{r}
statscan_employment <- readr::read_csv(here::here("inputs/data/raw_statscan_employment.csv"))
```

```{r}
# We would like to filter out the employment information:
# 1. In Ontario, 
# 2. Belongs to accommodation and food services category according to (NAICS) the North American Industry Classification System
# 3. In 2016 ( since we would use population density data in 2016 to perform city selection as treatment city and control city)
cleaned_statscan_employment <- 
  statscan_employment %>% 
  filter(
    grepl("Ontario", statscan_employment$GEO) &
    grepl("Accommodation and food services", statscan_employment$`North American Industry Classification System (NAICS)`) &
    grepl("^2016", statscan_employment$REF_DATE)
    )
# save the cleaned data
write_csv(cleaned_statscan_employment, here::here("inputs/data/cleaned_statscan_employment.csv"))
```


```{r}
# Read in the Population and Dwelling Count Highlight Tables, 2016 Census downloaded from Statistics Canada
# to get the population density data
# Link: https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/hlt-fst/pd-pl/Table.cfm?Lang=Eng&T=311&SR=1&S=87&O=A&RPP=9999&PR=35#details-panel2
# Note: We applied the filter on geography: provinces and territories to Ontario
raw_2016_census <- readr::read_csv(here::here("inputs/data/T31120210212123500.CSV")) # The original name of Population and Dwelling Count Highlight Tables, 2016 Census from Statistics Canada
```
```{r}
# We would like to filter out the census information:
# 1. In "City" of the CSD, DPL (census subdivision, designated place) type
cleaned_2016_census <- 
  raw_2016_census %>% 
  filter(
    grepl("City", raw_2016_census$`CSD, DPL Type`) 
    )
```

## Part 2 intervention decision

```{r}
# compare the number of observations between the cleaned_statscan_employment dataset and the cleaned_2016_census dataset
count(cleaned_statscan_employment) < count(cleaned_2016_census)
# We notice that the employment information is not available for all cities in the employment by industry dataset. 
# So we have to select the treatment city and the control city with employment information available
select_employment <- 
  cleaned_statscan_employment %>% 
  select(GEO, VALUE) %>% 
  filter(GEO != "Ottawa-Gatineau, Ontario/Quebec" & GEO != "Ottawa-Gatineau, Quebec part, Ontario/Quebec")
# Remove the Gatineau employment data since it is out of Ontario province

# We notice that the NAICS data about employment could be collected in city groups ( e.g. St. Catharines and Niagara are collected in a single subgroup)
city_groups <-
  cleaned_statscan_employment %>% 
  filter(grepl("-", cleaned_statscan_employment$GEO)) # Cities within the city group are separated by "-"
head(city_groups)

# So instead of directly using the Population density per square kilometer, we would like to select "the Land area in square kilometres, 2016" and "Population, 2016" to calculate the the weighted average of population density in the city groups.
select_census_poparea <- 
  cleaned_2016_census %>% 
  select( City = `Geographic name`, Population = `Population, 2016`, Area = `Land area in square kilometres, 2016`)
head(select_census_poparea)

select_census <- 
   cleaned_2016_census %>% 
  select( City = `Geographic name`, Population_Density = `Population density per square kilometre, 2016`)
head(select_census)
```


```{r}
library(stringr)
```



```{r}
# split the column name in select_employment dataset to remove "Ontario" province separated by comma
select_employment$City <- str_split_fixed(select_employment$GEO, ",", 2)[,1] #[,1] means to only keeps the city names column
# Drop the GEO column 
# Ref link to drop the column: https://stackoverflow.com/questions/6286313/remove-an-entire-column-from-a-data-frame-in-r
select_employment$GEO <- NULL

# change Ottawa-Gatineau into Ottawa since already removed Gatineau 
# Ref link to reassign value:https://www.edureka.co/community/35430/how-change-the-value-variable-using-programming-data-frame
select_employment$City[select_employment$City == "Ottawa-Gatineau"] <- "Ottawa"

unique(cleaned_statscan_employment$SCALAR_FACTOR)
# Multiply the employment value by 1000 since the scalar factor is in thousands 
select_employment$Employment <- select_employment$VALUE * 1000
# Drop the VALUE column
select_employment$VALUE <- NULL
select_employment
```
```{r}
# We would manually sum up the population and land area of 
# 1. St. Catharines and Niagara
# 2. Kitchener, Cambridge, and Waterloo
# And then calculate the population density of cities, including these city groups
# Ref link to add observations to a data frame: https://www.dummies.com/programming/r/how-to-add-observations-to-a-data-frame-in-r/

Catharines_Niagara <-
  select_census %>% 
  filter( City == "St. Catharines" | City == "Niagara Falls")

Catharines_Niagara
select_census <- 
  rbind(select_employment, c(
    "St. Catharines-Niagara", 
    
  ))

```


```{r}
# join two dataset to create a dataset that contains cities with population density and employment in Accommodation and food services available 
popdensity_employment <- merge(select_census, select_employment, by = "City")
popdensity_employment
```

```{r}
# Plot a Employment vs Population Density graph to detect cities with similar restaurant operating situation 
# (i.e. number of people served by restaurant staffs per square kilometers) by finding cities located closed to data points 
# 
ggplot( data = popdensity_employment, mapping = aes(x = Employment, y = Population_Density)) +
  geom_point( )+
  theme_minimal() + 
  geom_label_repel(aes( label = City)) +
  geom_smooth( method = "lm", formula = y~x)
```

```{r}
# The figure shows that Toronto has very high population density and employment in accommodation and food services, and it makes sense that Toronto is the most populous city in Canada
# Since we would like to select two cities with similar population density and employment as the treatment and control group, we remove Toronto from the graph due to no comparable restaurant operating situation with other cities.
popdensity_employment <- 
  popdensity_employment %>% 
  filter( City !="Toronto")

ggplot( data = popdensity_employment, mapping = aes(x = Employment, y = Population_Density)) +
  geom_point( )+
  theme_minimal() + 
  geom_label_repel(aes( label = City)) 
  #geom_smooth( method = "lm", formula = y~x)
#ggsave("city_selection.png")
```

```{r}
popdensity_employment$density_employment <- 
  popdensity_employment$Population_Density/ popdensity_employment$Employment
popdensity_employment
```
```{r}
# we would also like to compare the similarity between Brantford and Peterborough in turns of population and land area
select_census_poparea %>% 
  filter( City == "Brantford"| City == "Peterborough")
# The result shows that Brantford and Peterborough are similar cities in turns of population and area, expect that Brantford is slightly bigger and populus
```

```{r}
library(rvest)
```
```{r}
raw_census_data <- read_html("https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/hlt-fst/pd-pl/Table.cfm?Lang=Eng&T=311&SR=1&S=87&O=A&RPP=9999&PR=35#details-panel2")
write_html(raw_census_data, here("inputs/htmls/census.html"))
```


```{r}
parse_census_data <- 
  raw_census_data %>% 
  html_nodes("#COLGROUP2 , #COLGROUP1 , .text-left , #tablesort div , #tPopDwell .text-right") %>% 
  html_text()
```

```{r}
head(parse_census_data,100)
```










